### ISSUE TITLE
`getPlayerPosition` and `getPlayerTilePosition` are equivalent

### ISSUE THREAD

**Issue by nhatdongdang** [rozukke/mcpp#30]
## Description ##
The `Coordinate` class currently only supports integer fields. This limitation causes the `getPlayerPosition` method to behave the same as `getPlayerTilePosition`, and `setPlayerPosition` to behave the same as `setPlayerTilePosition`.

**Comment by rozukke** [comment]
I don't think the float/integer is what does it in this case, after double-checking the server-side code it seems like the error is on the Java side, as the naming implies something it is not doing. It seems to be a stayover from the old RaspberryPi version of the code, and we can implement a manual simple -1 to the Y position to emulate expected behaviour.

**Comment by johnathanchann** [comment]
I will work on this.
